export const ALLERGENS = [
	"Peanut-Free",
	"Sesame-Free",
	"Dairy-Free",
	"Gluten-Free",
	"Wheat-Free",
	"Egg-Free",
	"Kosher",
	"Soy-Free",
	"Pork-Free",
	"Shellfish-Free",
	"Alcohol-Free",
	"Red-Meat-Free",
	"Fish-Free",
	"Vegetarian",
];
